yatube/api/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'posts', views.PostViewSet)
router.register(r'users', views.UserViewSet)

app_name = 'api'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('v1/', include(router.urls)),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # path(
    #     'api/v1/api-token-auth/',
    #     obtain_auth_token,
    # ),
    # path(
    #     'api/v1/posts/<int:pk>/',
    #     views.api_post_detail,
    #     name='api_post_detail'
    # ),
    # path(
    #     'api/v1/posts/',
    #     views.api_posts,
    #     name='api_posts'
    # )
    # path(
    #     'api/v1/posts/',
    #     views.APIPostList.as_view()
    # ),
    # path(
    #     'api/v1/posts/<int:pk>/',
    #     views.APIPostDetail.as_view()
    # ),
]

yatube/posts/urls.py
from django.urls import path, include
# from rest_framework.authtoken.views import obtain_auth_token
# from rest_framework.routers import SimpleRouter

from . import views

# router = SimpleRouter()
# router.register('posts', views.PostViewSet)

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Список постов
    path('group_posts/<slug:slug>/', views.group_posts, name='group'),
    # Подробная информация по выбранному посту
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    # path(
    #     'api/v1/', include(router.urls)
    # ),
    # path(
    #     'api/v1/api-token-auth/',
    #     obtain_auth_token,
    # ),
    # path(
    #     'api/v1/posts/<int:pk>/',
    #     views.api_post_detail,
    #     name='api_post_detail'
    # ),
    # path(
    #     'api/v1/posts/',
    #     views.api_posts,
    #     name='api_posts'
    # )
    # path(
    #     'api/v1/posts/',
    #     views.APIPostList.as_view()
    # ),
    # path(
    #     'api/v1/posts/<int:pk>/',
    #     views.APIPostDetail.as_view()
    # ),
]

yatube/users/urls.py
# Импортируем необходимые классы
from django.contrib.auth.views import (LogoutView, LoginView,
                                       PasswordResetView, PasswordResetDoneView,
                                       PasswordResetConfirmView, PasswordResetCompleteView,
                                       PasswordChangeView, PasswordChangeDoneView)
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html',),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'
    ),

    # path(
    #     'new_request',
    #     views.user_contact().as_view(),
    #     name='new_request'
    # )
]

yatube/yatube/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import djoser
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('', include('posts.urls', namespace='posts'), ),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls', namespace='api'))
]
handler404 = 'core.views.page_not_found'
schema_view = get_schema_view(
   openapi.Info(
      title="Posts API",
      default_version='v1',
      description="Документация для приложения post проекта Yatube-project",
      # terms_of_service="URL страницы с пользовательским соглашением",
      contact=openapi.Contact(email="admin@post.ru"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)
urlpatterns += [
    url(r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/errors.html
<!-- templates/includes/errors.html -->

{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<!-- templates/includes/footer.html -->

<!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
<!-- templates/includes/header.html -->
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube</a>
    </a>

    <ul class="nav nav-pills">

      <li class="nav-item">
        <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
           href="{% url 'about:author' %}">Об авторе</a>

      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
           href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}"
           href="{% url 'posts:post_create' %}">Новая запись</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name == 'users:password_change' %}active{% endif %}"
           href="{% url 'users:password_change' %}">Изменить пароль</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li>
        Пользователь: {{ user.username }}
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link {% if view_name == 'users:login' %}active{% endif %}"
           href="{% url 'users:login' %}">Войти</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name == 'users:signup' %}active{% endif %}"
           href="{% url 'users:signup' %}">Зарегистрироваться</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endwith %}

yatube/templates/includes/paginator.html
<!-- templates/includes/paginator.html -->

<!-- Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу -->
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif%}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <span class="page-link">{{ i }}</span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif%}
  </ul>
</nav>
{% endif %}

yatube/templates/includes/switcher.html
<!-- templates/posts/includes/switcher.html -->

{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs justify-content-center">
      <li class="nav-item">
        <a
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}">
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link {% if follow %}active{% endif %}"
          href="{% url 'posts:follow_index' %}">
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}