yatube/api/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'posts', views.PostViewSet)
router.register(r'users', views.UserViewSet)

app_name = 'api'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('v1/', include(router.urls)),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # path(
    #     'api/v1/api-token-auth/',
    #     obtain_auth_token,
    # ),
    # path(
    #     'api/v1/posts/<int:pk>/',
    #     views.api_post_detail,
    #     name='api_post_detail'
    # ),
    # path(
    #     'api/v1/posts/',
    #     views.api_posts,
    #     name='api_posts'
    # )
    # path(
    #     'api/v1/posts/',
    #     views.APIPostList.as_view()
    # ),
    # path(
    #     'api/v1/posts/<int:pk>/',
    #     views.APIPostDetail.as_view()
    # ),
]

yatube/posts/urls.py
from django.urls import path, include
# from rest_framework.authtoken.views import obtain_auth_token
# from rest_framework.routers import SimpleRouter

from . import views

# router = SimpleRouter()
# router.register('posts', views.PostViewSet)

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Список постов
    path('group_posts/<slug:slug>/', views.group_posts, name='group'),
    # Подробная информация по выбранному посту
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    # path(
    #     'api/v1/', include(router.urls)
    # ),
    # path(
    #     'api/v1/api-token-auth/',
    #     obtain_auth_token,
    # ),
    # path(
    #     'api/v1/posts/<int:pk>/',
    #     views.api_post_detail,
    #     name='api_post_detail'
    # ),
    # path(
    #     'api/v1/posts/',
    #     views.api_posts,
    #     name='api_posts'
    # )
    # path(
    #     'api/v1/posts/',
    #     views.APIPostList.as_view()
    # ),
    # path(
    #     'api/v1/posts/<int:pk>/',
    #     views.APIPostDetail.as_view()
    # ),
]

yatube/yatube/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import djoser
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('', include('posts.urls', namespace='posts'), ),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls', namespace='api'))
]
handler404 = 'core.views.page_not_found'
schema_view = get_schema_view(
   openapi.Info(
      title="Posts API",
      default_version='v1',
      description="Документация для приложения post проекта Yatube-project",
      # terms_of_service="URL страницы с пользовательским соглашением",
      contact=openapi.Contact(email="admin@post.ru"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)
urlpatterns += [
    url(r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel
from .validators import validate_not_empty

# создание таблицы юзеров из шаблона Django.
User = get_user_model()


class Tag(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


# Создание экземпляра постов
class Group(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, db_index=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(validators=[validate_not_empty],
                            verbose_name='Текст поста',
                            help_text='Введите текст поста')

    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации',)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               verbose_name='Автор',
                               related_name='posts')
    group = models.ForeignKey(Group,
                              blank=True,
                              null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts',
                              verbose_name='Группа',
                              help_text='Выберите группу')
    # Поле для картинки (необязательное)
    image = models.ImageField(
        'картинка',
        upload_to='posts/',
        blank=True,
        null=True,
    )
    tag = models.ManyToManyField(Tag, through='TagPost')

    class Meta:
        ordering = ('-pub_data',),
        verbose_name = 'Пост',
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text


class TagPost(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.tag} {self.post}'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст отзыва',
        help_text='Введите текст отзыва'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Укажите подписчика',
        related_name='follower',
        help_text='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Укажите на кого подписываемся',
        related_name='following',
        help_text='Автор поста'
    )

    class Meta:
        ordering = ('-user',)
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = (
            models.UniqueConstraint(
                fields=('user', 'author'),
                name='unique_follows',
            ),
        )

    def __str__(self) -> str:
        return f'{self.user.username} подписан на {self.author.username}'

yatube/posts/forms.py
from django import forms
from .models import Post, Comment

MIN_POST_LEN = 30


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)

    def clean_text(self):
        data = self.cleaned_data['text']

        if len(data) <= MIN_POST_LEN:
            raise forms.ValidationError(
                f'Длина поста должна быть не менее {MIN_POST_LEN} символов!'
            )
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

# from . import serializer
from .forms import PostForm, CommentForm
# from django.contrib.auth.decorators import login_required

from .models import Post, Group, User, Follow
from api.serializer import PostSerializer


# def index(request):
#     # template = 'posts/index.html'
#     author = User.objects.get(username='leo')
#     start_date = datetime.date(1854, 7, 7)
#     end_date = datetime.date(1854, 7, 21)
#     keyword = 'утро'
#     title = 'Последние обновления на сайте'
#     # posts = Post.objects.order_by('-pub_date')[0:3]
#     posts = Post.objects.filter(text__contains=keyword).filter(author=author.id).filter(pub_date__range=(start_date, end_date))
#     context = {
#         'title': title,
#         # 'text': 'Это главная страница проекта Yatube'
#         'posts': posts
#     }
#     return render(request, 'posts/index.html', context)
# def index(request):
#     keyword = request.GET.get('q', None)
#     if keyword:
#         posts = Post.objects.filter(text__contains=keyword).select_related('author').select_related('group')
#     else:
#         posts = None
#     return render(request, 'posts/index.html', {'posts': posts})
def authorized_only(func):
    def check_user(request, *args, **kwargs):
        if request.user.is_authenticated:
            return func(request, *args, **kwargs)
        return redirect('/auth/login/')
    return check_user


# @login_required
@cache_page(20)
def index(request):
    title = 'Последние обновления на сайте'
    # Создаем список постов
    post_list = Post.objects.all().order_by('-pub_date')
    # post_list = Post.objects.all()
    # Создаем пагинатор для отображения 10 страниц
    paginator = Paginator(post_list, 10)
    # Из URL извлекаем номер страницы - это значение параметра page
    page_number = request.GET.get('page')
    # Получаем набор записей для страницы
    page_obj = paginator.get_page(page_number)
    # Отдаем в словаре контекста
    context = {
        'page_obj': page_obj,
        'title': title,
    }
    return render(request, 'posts/index.html', context)


# @authorized_only
def group_posts(request, slug):
    # template = 'posts/group_list.html'
    # desc = 'Здесь будет информация о группах проекта Yatube'
    # context = {'desc': desc}
    # return render(request, template, context)
    # title = 'Лев Толстой - зеркало русской революции.'
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')
    title = group.title
    # Создаем пагинатор для отображения 10 страниц
    paginator = Paginator(posts, 10)
    # Из URL извлекаем номер страницы - это значение параметра page
    page_number = request.GET.get('page')
    # Получаем набор записей для страницы
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


@authorized_only
def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author_id=author.id).order_by('-pub_date')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = author.get_full_name
    quantity_posts = author.posts.count()
    followers = Follow.objects.filter(author__username=username).count()

    context = {
        'title': title,
        'page_obj': page_obj,
        'author': author,
        'quantity_posts': quantity_posts,
        'followers': followers,
        'following': False,
    }
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            author=author,
            user=request.user,
        ).exists()
        context.update({
            'following': following,
            'user': request.user,
        })
    return render(request, 'posts/profile.html', context)


# @authorized_only
def post_detail(request, post_id):

    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    form_comment = CommentForm()
    title = post.text[:30]
    quantity_posts = post.author.posts.count()
    context = {
        'title': title,
        'post': post,
        'quantity_posts': quantity_posts,
        'comments': comments,
        'form': form_comment,
    }
    return render(request, 'posts/post_detail.html', context)


# @authorized_only
@login_required(login_url='users:login')
def post_create(request):

    if request.method == 'POST':
        # Создаем объект формы PostForm
        # И передаем в него полученные данные
        form = PostForm(request.POST or None,
                        files=request.FILES or None,)

        # Если данные валидны - работаем с "очищенными" данными
        if form.is_valid():
            text = form.cleaned_data['text']
            group = form.cleaned_data['group']

            instance = form.save(commit=False)
            instance.author_id = request.user.id
            instance.save()
            user_name = request.user.username

            # Перенаправляем на другую страницу, чтобы защититься от повторного заполнения
            return redirect('posts:profile', user_name)

        return render(request, 'posts/create_post.html', {'form': form})

    # Если пришел не пост запрос - передаем пустую форму
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required(login_url='users:login')
def post_edit(request, post_id):
    """Функция редактирования поста"""

    # Находим необходимый пост
    post = get_object_or_404(Post, pk=post_id)

    if request.user.id != post.author.id:
        return redirect('posts:post_detail', post.pk)

    if request.method == 'POST':

        form = PostForm(request.POST or None, files=request.FILES or None, instance=post)

        # Если данные валидны - работаем с "очищенными" данными
        if form.is_valid():
            # text = form.cleaned_data['text']
            # group = form.cleaned_data['group']
            #
            # instance = form.save(commit=False)
            # instance.author_id = request.user.id
            # instance.save()
            form.save()
            user_name = request.user.username

            # Сохраняем данные

            # Перенаправляем на другую страницу, чтобы защититься от повторного заполнения
            return redirect('posts:profile', user_name)

        return render(request, 'posts/create_post.html', {'form': form})

        # Если пришел не пост запрос - передаем пустую форму
    form = PostForm(instance=post)
    context = {'post': post, 'form': form,
               'is_edit': True}
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    """Функция добавления комментария"""
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post.pk)


@login_required
def follow_index(request):
    """Функция просмотра подписчиков"""
    title = 'Подписки пользователей'
    # Создаем список постов
    post_list = Follow.objects.filter(author__following__user=request.user)
    # Создаем пагинатор для отображения 10 страниц
    paginator = Paginator(post_list, 10)
    # Из URL извлекаем номер страницы - это значение параметра page
    page_number = request.GET.get('page')
    # Получаем набор записей для страницы
    page_obj = paginator.get_page(page_number)
    # Отдаем в словаре контекста
    context = {
        'page_obj': page_obj,
        'title': title,

    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Функция подписки на автора"""
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(
            user=user,
            author=author,
        )

    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Функция отписки от автора"""
    author = get_object_or_404(User, username=username)

    unfollow = Follow.objects.filter(
        user=request.user,
        author=author
    )
    if unfollow.exists():
        unfollow.delete()

    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
<!-- templates/posts/create_post.html -->

{% extends 'base.html' %}
{% block title %}{% if is_edit%}Редактировать запись{% else %}Новый пост{% endif %}{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}
        </div>
        <div class="card-body">
          {% include 'includes/errors.html' %}

          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {{ field }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}

            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}Сохранить{% else %}Добавить{% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/create_post_old.html
<!-- templates/posts/create_post.html -->

{% extends 'base.html' %}
{% block title %}{% if is_edit %}Редактировать запись{% else %}Добавить{% endif %}{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}Редактировать запись{% else %}Добавить{% endif %}
        </div>
        <div class="card-body">
          {% include 'includes/errors.html' %}
          <form method="post" action="{{ request.get_full_path }}">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {{ field }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
            {% endfor %}

            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% block title %}Подписки пользователей{% endblock %}
{% block content %}
  {% include 'includes/switcher.html' %}
  {% for post in page_obj %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
    <div class="container py-5">
        <ul>
          <li>
            {% if post.author.get_full_name %}
            Автор: {{ post.author.get_full_name }}
            {% else %}
            Автор: {{ post.author.username }}
            {% endif %}
            <a href="{% url 'posts:profile' post.author.username  %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" upscale=True as im %}
          <img src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        {% if post.group %}
          <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}
          <hr>{% endif %}
    </div>
  {% endfor %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
    <h1>{{ title }}</h1>
    <p>
        {{ group.description }}
    </p>
    <article>
        {% for post in page_obj %}
        <ul>
            <li>
              {% if post.author.get_full_name %}
                Автор: {{ post.author.get_full_name }}
              {% else %}
                Автор: {{ post.author.username }}
              {% endif %}

                <a href="{% url 'posts:profile' post.author.username  %}">все посты пользователя</a>
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
        </ul>
        {% thumbnail post.image "960x339" upscale=True as im %}
          <img src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        {% if not forloop.last %}
        <hr>{% endif %}
        {% endfor %}
    </article>
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  {% cache 20 index_page %}
  {% for post in page_obj %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
    <div class="container py-3">
        <ul>
          <li>
            {% if post.author.get_full_name %}
            Автор: {{ post.author.get_full_name }}
            {% else %}
            Автор: {{ post.author.username }}
            {% endif %}
            <a href="{% url 'posts:profile' post.author.username  %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" upscale=True as im %}
          <img src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        {% if post.group %}
          <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}
          <hr>{% endif %}
    </div>
  {% endfor %}
  {% endcache %}
{% endblock %}

yatube/templates/posts/index1.html
<!-- templates/posts/index1.html -->
<!DOCTYPE html>
<html lang="ru">
  <head>

  </head>
  <body>
    <h1>Главная страница</h1>
  </body>
</html>

yatube/templates/posts/post_detail.html
<!-- templates/posts/post_detail.html -->

{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content%}
{% load user_filters %}
{% load thumbnail %}

<div class="row">

  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group.title }}
          <a href="{% url 'posts:group' post.group.slug %}">
            все записи группы
          </a>
        </li>
      {% endif %}
        <li class="list-group-item">
         {% if post.author.get_full_name %}
            Автор: {{ post.author.get_full_name }}
          {% else %}
            Автор: {{ post.author.username }}
          {% endif %}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span >{{ quantity_posts }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username  %}">Все посты пользователя</a>
        </li>
    </ul>

  </aside>
  <article class="col-12 col-md-9">

    {% thumbnail post.image "960x339" upscale=True as im %}
      <img src="{{ im.url }}">
    {% endthumbnail %}

    <p>{{ post.text }}</p>
    {% if user.id == post.author.id %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
        редактировать запись
      </a>
    {% endif %}
    {% for comment in comments %}
    <div class="media mb-4">
      <div class="media-body">
        <h5 class="mt-4">
          <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.username }}
          </a>
        </h5>
        <p>
          {{ comment.text }}
        </p>
      </div>
    </div>
    {% endfor %}
    {% if user.is_authenticated %}
    <div class="card my-4">
      <h5 class="card-header">Добавить комментарий</h5>
      <div class="card-body">
        <form method="post" action="{% url 'posts:add_comment' post.id %}">
          {% csrf_token %}
          <div class="form-group mb-2">
            {{ form.text|addclass:"form-control" }}
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
      </div>
    </div>
    {% endif %}
  </article>
</div>
{% endblock %}

yatube/templates/posts/profile.html
<!-- templates/posts/profile.html -->

{% extends 'base.html' %}
{% block title %}{{ title }}{{ post.author.get_full_name }}{% endblock %}
{% block content %}
{% load user_filters %}
{% load thumbnail %}
<div class="container py-5 mb-5">
  <h1>Все посты пользователя {{ title }}</h1>
  <h3>Всего постов: {{ quantity_posts }}</h3>
  <h3>Всего подписчиков {{ followers }}</h3>
  {% if user.is_authenticated and author != user %}
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}"
      role="button">
      Отписаться
    </a>
  {% else %}
    <a
      class="btn btn-lg btn-primary"
      href="{% url 'posts:profile_follow' author.username %}"
      role="button">
      Подписаться
    </a>
  {% endif %}
  {% endif %}
  <hr>
  <article>
    {% for post in page_obj %}
    <ul>
 <!--     <li>
        {% if post.author.get_full_name %}
            Автор: {{ post.author.get_full_name }}
        {% else %}
            Автор: {{ post.author.username }}
        {% endif %}
        <br>
        <a href="{% url 'posts:profile' user.username  %}">все посты пользователя</a>
      </li> -->
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" upscale=True as im %}
      <img src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text }}
    </p>
    <a href="{% url 'posts:post_detail' post.id  %}">подробная информация </a>
    <br>
    {% if post.group %}
      <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}
      <hr>{% endif %}
    {% endfor %}
  </article>
</div>
{% endblock %}