yatube/api/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'posts', views.PostViewSet)
router.register(r'users', views.UserViewSet)

app_name = 'api'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('v1/', include(router.urls)),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # path(
    #     'api/v1/api-token-auth/',
    #     obtain_auth_token,
    # ),
    # path(
    #     'api/v1/posts/<int:pk>/',
    #     views.api_post_detail,
    #     name='api_post_detail'
    # ),
    # path(
    #     'api/v1/posts/',
    #     views.api_posts,
    #     name='api_posts'
    # )
    # path(
    #     'api/v1/posts/',
    #     views.APIPostList.as_view()
    # ),
    # path(
    #     'api/v1/posts/<int:pk>/',
    #     views.APIPostDetail.as_view()
    # ),
]

yatube/users/urls.py
# Импортируем необходимые классы
from django.contrib.auth.views import (LogoutView, LoginView,
                                       PasswordResetView, PasswordResetDoneView,
                                       PasswordResetConfirmView, PasswordResetCompleteView,
                                       PasswordChangeView, PasswordChangeDoneView)
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html',),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'
    ),

    # path(
    #     'new_request',
    #     views.user_contact().as_view(),
    #     name='new_request'
    # )
]

yatube/yatube/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import djoser
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('', include('posts.urls', namespace='posts'), ),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls', namespace='api'))
]
handler404 = 'core.views.page_not_found'
schema_view = get_schema_view(
   openapi.Info(
      title="Posts API",
      default_version='v1',
      description="Документация для приложения post проекта Yatube-project",
      # terms_of_service="URL страницы с пользовательским соглашением",
      contact=openapi.Contact(email="admin@post.ru"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)
urlpatterns += [
    url(r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField
    subject = models.CharField(max_length=100)
    body = models.TextField()
    is_answered = models.BooleanField(default=False)

yatube/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

# from .models import Contact

User = get_user_model()


# создадим класс для формы регистрации
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # Указываем модель, с которой связана форма
        model = User
        # Необходимые поля и их порядок
        fields = ('first_name', 'last_name', 'username', 'email')


# class ContactForm(forms):
#     class Meta:
#         # Но основе какой модели создается форма
#         model = Contact
#         # Указываем какие поля будут в форме
#         fields = ['name', 'email', 'subject', 'body']
#
#         # Метод валидатор для поля subject
#         def clean_subject(self):
#             data = self.cleaned_data['subject']
#
#             # Если пользователь не поблагодарит - считаем это ошибкой
#             if 'спасибо' not in data.lower():
#                 raise forms.ValidationError('Вы обязательно должны нас поблагодарить!')
#
#             # Валидатор обязательно должен вернуть очищенные данные, даже если не изменил их
#             return data

yatube/users/views.py
# Импортируем CreateView, чтобы создать насленика
from django.core.mail import send_mail
from django.shortcuts import render
from django.views.generic import CreateView

# Импортируем функцию reverse_lazy, которая позволяет получить URL по функции path()
from django.urls import reverse_lazy

# Импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm
# from .models import Contact


class SignUp(CreateView):
    form_class = CreationForm
    # После регистрации перенаправляем на главную
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

    # send_mail(
    #     'Тема письма',
    #     'Текст письма',
    #     'from@example.com',
    #     ['to@example.com'],
    #     fail_silently=False,
    # )

# def user_contact(request):
#     # запрашиваем объект модели Contact
#     contact = Contact.objects.get(pk=3)
#
#     # Создаем объект формы и передаем в него объект модели с pk=3
#     form = ContactForm(isinstance=contact)
#
#     # Передаем форму в HTML-шаблон
#     return render(request, 'users/contact.html', {'form': form})

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём Вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
<!-- templates/users/login.html -->

{% extends 'base.html' %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% include 'includes/errors.html' %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required='true'
              {% else %}
                aria-required='false'
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-8 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>

            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock%}

yatube/templates/users/password_change_done.html
<!-- templates/users/password_change_done.html -->

{% extends 'base.html' %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 py-5">
      <div class="card">
        <div class="card-header">
          Пароль изменён
        </div>
        <div class="card-body">
          <p>Пароль изменён успешно</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_change_form.html
<!-- templates/users/password_change_form.html -->

{% extends 'base.html' %}
{% block title %}Смена пароля{% endblock %}
{% block content %}
{% load user_filters %}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
        {% load user_filters %} {# Загружаем фильтры #}
        {# Этот блок будет показан, если в форме есть ошибки #}
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}

          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}

        <form method="post"
          {% if action_url %}
            action="{% url action_url %}"
          {% endif %}
        >
        {% csrf_token %}
          <div class="form-group row my-3 p-3">
            <label for="id_old_password">
              Старый пароль
              <span class="required text-danger">*</span>
            </label>
            <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
          </div>
          <div class="form-group row my-3 p-3">
            <label for="id_new_password1">
              Новый пароль
              <span class="required text-danger">*</span>
            </label>
            <input type="password" name="new_password1" autofocus class="form-control" required id="id_new_password1">
              <small id="id_new_password1-help" class="form-text text-muted">
                <ul>
                  <li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на нее</li>
                  <li>Ваш пароль должен содержать как минимум 8 символов</li>
                  <li>Ваш пароль не может быть одним из широко распространённых паролей</li>
                  <li>Ваш пароль не может состоять только из цифр</li>
                </ul>
              </small>
          </div>
          <div class="form-group row my-3 p-3">
            <label for="id_new_password2">
              Подтверждение нового пароля
              <span class="required text-danger">*</span>
            </label>
            <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
          </div>
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Изменить пароль
            </button>
          </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

yatube/templates/users/password_reset_complete.html
<!-- templates/users/password_reset_complete.html -->

{% extends 'base.html' %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 py-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранён. Используйте его для входа</p>
          <a href="{% url 'users:login' %}">Войти</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
<!-- templates/users/password_reset_confirm.html -->

{% extends 'base.html' %}
{% block title %}Смена пароля{% endblock %}
{% block content %}
{% load user_filters %}

{% if validlink %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    Введите новый пароль
                </div>
                <div class="card-body">
                  {% load user_filters %} {# Загружаем фильтры #}
                  {# Этот блок будет показан, если в форме есть ошибки #}
                  {% if form.errors %}
                    {% for field in form %}
                      {% for error in field.errors %}
                        <div class="alert alert-danger">
                          {{ error|escape }}
                        </div>
                      {% endfor %}
                    {% endfor %}

                    {% for error in form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endif %}

                  <form method="post"
                    {% if action_url %}
                      action="{% url action_url %}"
                    {% endif %}
                  >
                  {% csrf_token %}
                    <div class="form-group row my-3 p-3">
                      <label for="id_new_password1">
                        Новый пароль
                        <span class="required text-danger">*</span>
                      </label>
                      <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                        <small id="id_new_password1-help" class="form-text text-muted">
                          <ul>
                            <li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на нее</li>
                            <li>Ваш пароль должен содержать как минимум 8 символов</li>
                            <li>Ваш пароль не может быть одним из широко распространённых паролей</li>
                            <li>Ваш пароль не может состоять только из цифр</li>
                          </ul>
                        </small>
                    </div>
                    <div class="form-group row my-3 p-3">
                      <label for="id_new_password2">
                        Подтверждение нового пароля
                        <span class="required text-danger">*</span>
                      </label>
                      <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                    </div>
                    <div class="col-md-6 offset-md-4">
                      <button type="submit" class="btn btn-primary">
                        Назначить новый пароль
                      </button>
                    </div>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Ошибка</div>
      <div class="card-body">
        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
<!-- templates/users/password_reset_done.html -->

{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 py-5">
      <div class="card">
        <div class="card-header">
          Отправлено письмо
        </div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_form.html
<!-- templates/users/password_reset_form.html -->

{% extends 'base.html' %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 py-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль - введите адрес электронной почты, под которым вы регистрировались
        </div>
        <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% if form.errors %}
          {% for field in form %}
          {% for error in field.errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
          {% endfor %}
          {% endfor %}

          {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
          {% endfor %}
          {% endif %}

          <form method="post"
                {% if action_url %}
                action="{% url action_url %}"
                {% endif %}
          >
          {% csrf_token %}
          <div class="form-group row my-3 p-3">
            <label for="id_email">
              Адрес электронной почты
            </label>
            <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
          </div>
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Сбросить пароль
            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
<!-- templates/users/signup.html -->

{% extends 'base.html' %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
          {# Этот блок будет показан, если в форме есть ошибки #}
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}

            <form method="post" action={% url 'users:signup' %}>
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3">
                <label for={{ field.id_for_label }}>
                  {{ field.label}}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {# К полю ввода добавляем атрибут class #}
                {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}